# Generated by Django 2.2 on 2021-10-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwizwhiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
